version: 2
jobs:
  build:
    working_directory: ~
    docker: 
      - image: circleci/node:9
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: test
          command: npm run test-ci
      - run: 
          name: code-coverage
          command: npm run coverage
          environment:
            JEST_JUNIT_OUTPUT: "junit.xml"
      - store_artifacts: 
          path: junit.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: junit.xml